language: node_js

node_js:

  - 10.16.0

before_script:
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 5
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:

  - npm run start-babel
  - cd client && nmp install
